import sys
if 'win' in sys.platform:
	env = Environment(tools = ['mingw'])
	name = 'treque'
else:
	env = Environment()
	name = 'treque.out'

env.Append(
	CXXFLAGS=[
		'-g',
		'-Wall',
		'-pedantic',
		'-Wall',
		'-Wextra',
		'-Wcast-align',
		'-Wcast-qual',
		'-Wctor-dtor-privacy',
		'-Wdisabled-optimization',
		'-Wformat=2',
		'-Winit-self',
		'-Wlogical-op',
		'-Wmissing-declarations',
		'-Wmissing-include-dirs',
		'-Wnoexcept',
		'-Woverloaded-virtual',
		'-Wredundant-decls',
		'-Wshadow',
		'-Wsign-conversion',
		'-Wsign-promo',
		'-Wstrict-null-sentinel',
		'-Wstrict-overflow=5',
		'-Wswitch-default',
		'-Wundef',
		'-Werror',
		'-Wno-unused'
	]
)

target = env.Program(name, Glob('src/*.cpp'))
