import sys
if 'win' in sys.platform:
	debug = Environment(tools = ['mingw'])
	release = Environment(tools = ['mingw'])
else:
	debug = Environment()
	release = Environment()

debug.Append(CCFLAGS=['-g'])

debug.Program('treque_test', Glob('src/*.cpp'))
release.Program('treque', Glob('src/*.cpp'))

release.Alias('release')

Default(debug)