import sys
if 'win' in sys.platform:
	debug = Environment(tools = ['mingw'])
	release = Environment(tools = ['mingw'])
else:
	debug = Environment()
	release = Environment()

debug.Append(CXXFLAGS=['-g', 'Wall'])

release_object = release.Object('treque', Glob('src/*.cpp'))
release_target = release.Program(release_object)
release.Alias('release', release_target)

debug_object = release.Object('treque-dbg', Glob('src/*.cpp'))
debug_target = debug.Program(debug_object)
debug.Default(debug_target)
